### ISSUE TITLE
This is Evil

### ISSUE THREAD

**Issue by Adrien-Tab** [HyperLan-git/shidbot#1]
https://github.com/HyperLan-git/shidbot/blame/7374df823c80ca89243b4521663efdd36bb8cd0d/src/commands/voice/randsfx.js#L28

**Comment by HyperLan-git** [comment]
Not really since you can do the leave command and the bot will leave the voice chat. But yeah I guess the loop could still be running and using resources? Don't care all of this is a shitpost.
The goal of this command was to replace the instances when my friends would play videos titled "1h of silence interrupted by X" so that's why it lasts an hour.

**Comment by HyperLan-git** [comment]
Nothing to do here
